### ISSUE TITLE
Support for recursive parent-child trees

### ISSUE THREAD

**Issue by MarcelHeemskerk** [ouxuyong/jolt-universe#2]
Please see https://github.com/bazaarvoice/jolt/issues/1172

Maybe add the solution here as example?

**Comment by ouxuyong** [comment]
You need to copy 'recursiveReplacement' into your 'java' code.

Your example, I'll give you an example after get off work tonight
@MarcelHeemskerk

**Comment by ouxuyong** [comment]
The effect you want to achieve 'recursiveReplacement' does not satisfy you, you need to write an additional custom method, I will try to write it later @MarcelHeemskerk

**Comment by ouxuyong** [comment]
@MarcelHeemskerk  customized an implementation of 'jolt', you can copy[JoltCustomizedFunction](https://github.com/ouxuyong/jolt-universe/blob/master/src/main/java/com/example/oxy/jolt/JoltCustomizedFunction.java) and [JoltCustomizedModifier](https://github.com/ouxuyong/jolt-universe/blob/master/src/main/java/com/example/oxy/jolt/JoltCustomizedModifier.java) into your project, then change 'com.example.oxy.jolt.JoltCustomizedModifier$Overwrite' to the path in your project to achieve the effect you want
This is the test demo [CustomizedTest](https://github.com/ouxuyong/jolt-universe/blob/master/src/test/java/com/example/oxy/customized/CustomizedTest.java) ,there is a jolt tutorial project.

input:
```json
{
  "Name": "Mike",
  "Age": 50,
  "Hobbies": [
    {
      "id": 2,
      "name": "painting"
    }
  ],
  "Children": [
    {
      "Name": "MikeSon",
      "Age": 30,
      "Hobbies": [
        {
          "id": 1,
          "name": "painting"
        } ,
        {
          "id": 2,
          "name": "squash"
        }
      ],
      "Children": [
        {
          "Name": "MikeGrandSon",
          "Age": 10,
          "Hobbies": [],
          "Children": []
        },
        {
          "Name": "MikeGrandDaughter",
          "Age": 5,
          "Hobbies" : [
            {
              "id": 3,
              "name": "playing"
            }
          ],
          "Children": []
        }
      ]
    }
  ]
}
```
spec:

```json
[
  {
    "operation": "shift",
    "spec": {
      "Name": "FirstName",
      "Age": "Age",
      "Hobbies": {
        "*": {
          "name": "Hobbies"
        }
      },
      "Children": "Children"
    }
  },{
  "operation": "com.example.oxy.jolt.JoltCustomizedModifier$Overwrite",
  "spec": {
    "Children": "=recursiveOperation(@(1,Children),Children,Name->FirstName,=concat(Hobbies.name->Hobbies))"
  }
}
]
```
Output:

```json
{
	"FirstName": "Mike",
	"Age": 50,
	"Hobbies": "painting",
	"Children": [{
		"Age": 30,
		"Hobbies": "painting,squash",
		"Children": [{
			"Age": 10,
			"Hobbies": "",
			"Children": [],
			"FirstName": "MikeGrandSon"
		}, {
			"Age": 5,
			"Hobbies": "playing",
			"Children": [],
			"FirstName": "MikeGrandDaughter"
		}],
		"FirstName": "MikeSon"
	}]
}
```

**Comment by MarcelHeemskerk** [comment]
@ouxuyong  xie xie!
